"""Isolated capability implementations; none are model-visible yet."""

from app.capabilities.contracts import (
    Capability,
    CapabilityArgumentError,
    CapabilityContext,
    CapabilityErrorCode,
    CapabilityExecutionError,
    CapabilityFailure,
    CapabilityResult,
    ExecutionIsolation,
    PermissionClass,
)
from app.capabilities.filesystem_stat import FilesystemStatCapability
from app.capabilities.executor import (
    CapabilityExecutor,
    ExecutorLimits,
    ExecutorSnapshot,
)
from app.capabilities.crash_journal import (
    CallLifecycleRecord,
    CallLifecycleState,
    CapabilityCrashJournal,
    CrashJournalCorruptionError,
    CrashJournalError,
    CrashJournalPersistenceError,
    DuplicateCallIdError,
    JournaledCapabilityExecutor,
    JournalRetentionPolicy,
    LifecycleTransitionError,
)
from app.capabilities.permissions import (
    ApprovalManager,
    ApprovalNotFoundError,
    ApprovalRecord,
    ApprovalStatus,
    AuthorizationCode,
    PermissionAuthorization,
    PermissionDecision,
    PermissionEvaluation,
    PermissionGate,
    PermissionRequest,
    PermissionRule,
    PreparedCapabilityCall,
    prepare_capability_call,
)
from app.capabilities.registry import (
    CapabilityLookupError,
    CapabilityRegistration,
    CapabilityRegistry,
    CapabilityRegistryConfigurationError,
    ModelCapabilityDefinition,
    RegistryConfigurationCode,
)

__all__ = [
    "Capability",
    "CapabilityArgumentError",
    "CapabilityContext",
    "CapabilityErrorCode",
    "CapabilityExecutionError",
    "CapabilityFailure",
    "CapabilityResult",
    "CapabilityExecutor",
    "CallLifecycleRecord",
    "CallLifecycleState",
    "CapabilityCrashJournal",
    "CrashJournalCorruptionError",
    "CrashJournalError",
    "CrashJournalPersistenceError",
    "DuplicateCallIdError",
    "JournaledCapabilityExecutor",
    "JournalRetentionPolicy",
    "LifecycleTransitionError",
    "ApprovalManager",
    "ApprovalNotFoundError",
    "ApprovalRecord",
    "ApprovalStatus",
    "AuthorizationCode",
    "ExecutionIsolation",
    "ExecutorLimits",
    "ExecutorSnapshot",
    "CapabilityLookupError",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "CapabilityRegistryConfigurationError",
    "FilesystemStatCapability",
    "ModelCapabilityDefinition",
    "PermissionAuthorization",
    "PermissionClass",
    "PermissionDecision",
    "PermissionEvaluation",
    "PermissionGate",
    "PermissionRequest",
    "PermissionRule",
    "PreparedCapabilityCall",
    "RegistryConfigurationCode",
    "prepare_capability_call",
]
