"""Capability foundations; production visibility is owned by the explicit agent gate."""

from app.capabilities.contracts import (
    Capability,
    CapabilityArgumentError,
    CapabilityContext,
    CapabilityErrorCode,
    CapabilityExecutionError,
    CapabilityFailure,
    CapabilityResult,
    ExecutionIsolation,
    PermissionClass,
)
from app.capabilities.filesystem_stat import FilesystemStatCapability
from app.capabilities.filesystem_find import FilesystemFindCapability
from app.capabilities.filesystem_list import FilesystemListCapability
from app.capabilities.filesystem_read_text import FilesystemReadTextCapability
from app.capabilities.filesystem_search import FilesystemSearchCapability
from app.capabilities.executor import (
    CapabilityExecutor,
    ExecutorLimits,
    ExecutorSnapshot,
)
from app.capabilities.crash_journal import (
    CallLifecycleRecord,
    CallLifecycleState,
    CapabilityCrashJournal,
    CrashJournalCorruptionError,
    CrashJournalError,
    CrashJournalPersistenceError,
    DuplicateCallIdError,
    JournaledCapabilityExecutor,
    JournalRetentionPolicy,
    LifecycleTransitionError,
)
from app.capabilities.permissions import (
    ApprovalManager,
    ApprovalNotFoundError,
    ApprovalRecord,
    ApprovalStatus,
    AuthorizationCode,
    PermissionAuthorization,
    PermissionDecision,
    PermissionEvaluation,
    PermissionGate,
    PermissionRequest,
    PermissionRule,
    PreparedCapabilityCall,
    prepare_capability_call,
)
from app.capabilities.registry import (
    CapabilityLookupError,
    CapabilityRegistration,
    CapabilityRegistry,
    CapabilityRegistryConfigurationError,
    ModelCapabilityDefinition,
    RegistryConfigurationCode,
)

__all__ = [
    "Capability",
    "CapabilityArgumentError",
    "CapabilityContext",
    "CapabilityErrorCode",
    "CapabilityExecutionError",
    "CapabilityFailure",
    "CapabilityResult",
    "CapabilityExecutor",
    "CallLifecycleRecord",
    "CallLifecycleState",
    "CapabilityCrashJournal",
    "CrashJournalCorruptionError",
    "CrashJournalError",
    "CrashJournalPersistenceError",
    "DuplicateCallIdError",
    "JournaledCapabilityExecutor",
    "JournalRetentionPolicy",
    "LifecycleTransitionError",
    "ApprovalManager",
    "ApprovalNotFoundError",
    "ApprovalRecord",
    "ApprovalStatus",
    "AuthorizationCode",
    "ExecutionIsolation",
    "ExecutorLimits",
    "ExecutorSnapshot",
    "CapabilityLookupError",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "CapabilityRegistryConfigurationError",
    "FilesystemStatCapability",
    "FilesystemFindCapability",
    "FilesystemListCapability",
    "FilesystemReadTextCapability",
    "FilesystemSearchCapability",
    "ModelCapabilityDefinition",
    "PermissionAuthorization",
    "PermissionClass",
    "PermissionDecision",
    "PermissionEvaluation",
    "PermissionGate",
    "PermissionRequest",
    "PermissionRule",
    "PreparedCapabilityCall",
    "RegistryConfigurationCode",
    "prepare_capability_call",
]
